apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment-1
  labels:
    app.kubernetes.io/name: deploy-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-1
  template:
    metadata:
      labels:
        app: deploy-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: nginx
      - name: multitool
        image: wbitt/network-multitool
        env:
            - name: HTTP_PORT
              value: "1180"
        ports:
        - containerPort: 1180
          name: multitool
---
apiVersion: v1
kind: Service
metadata:
  name: netology-deployment-service
spec:
  selector:
    app: deploy-1
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: nginx
  - name: multitool
    protocol: TCP
    port: 1180
    targetPort: multitool