version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: pg
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./bd:/var/lib/postgresql/data
      - ./backup:/var/backups/pg_backup
    ports:
      - "5432:5432"
