---
- src: https://github.com/NotClove/netology-ansible-clickhouse.git
  scm: git
  version: "1.11.0"
  name: clickhouse 
- src: https://github.com/NotClove/netology-ansible-lighthouse.git
  scm: git
  version: "1.0"
  name: lighthouse 
- src: https://github.com/NotClove/netology-ansible-vector.git
  scm: git
  version: "0.26.1"
  name: vector 