{
 "title": "netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "CPU idle"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))",
     "legendFormat": "cpu 1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "cpu 5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))\n",
     "legendFormat": "cpu 15"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node_exporter:9100\", job=\"node-exporter\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_MemFree_bytes{instance=\"node_exporter:9100\"} - node_memory_Cached_bytes{instance=\"node_exporter:9100\"} - node_memory_Buffers_bytes{instance=\"node_exporter:9100\"}\n",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "HDD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\",instance=\"node_exporter:9100\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\",instance=\"node_exporter:9100\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}