apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment-2
  labels:
    app.kubernetes.io/name: deploy-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-2
  template:
    metadata:
      labels:
        app: deploy-2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: netology-deployment-service
spec:
  selector:
    app: deploy-2
  ports:
  - name: nginx
    protocol: TCP
    port: 9001
    targetPort: nginx
  type: NodePort
