apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-volume
  labels:
    app: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared
  template:
    metadata:
      labels:
        app: shared
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "num=0; while true; do let num++ && echo line $num >> /share/log.txt ; sleep 5; done"]
          volumeMounts:
          - mountPath: /share
            name: shared-volume
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
          - mountPath: /share
            name: shared-volume
          env:
            - name: HTTP_PORT
              value: "8080"
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
            claimName: pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /storage/
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi