apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app.kubernetes.io/name: hello
spec:
  containers:
  - name: nginx
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
      - containerPort: 8080
        name: netology-svc

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app.kubernetes.io/name: hello
  ports:
  - name: netology-web-port
    protocol: TCP
    port: 8080
    targetPort: netology-svc
